recordingRoots:
  - id: b888808a681c
    path: /recordings/XiaomiCamera_00_B888808A681C
    streams:
      - channel: "00"
        alias: "前院主摄"
  - id: b88880a344eb
    path: /recordings/XiaomiCamera_01_B88880A344EB
    streams:
      - channel: "00"
        alias: "空目录摄像头"
  - id: b888809544f6
    path: /recordings/xiaomi_camera_videos/B888809544F6
    streams:
      - channel: "00"
        alias: "双摄 A"
      - channel: "10"
        alias: "双摄 B"
